
services:

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: XMAS2024
      POSTGRES_PASSWORD: XMASPASSWORD
      POSTGRES_DB: pipeline

  backend:
    build: ./services/node-backend
    restart: always
    environment:
      ML_ADDRESS: mlflow:3000
      POSTGRES_USER: XMAS2024
      POSTGRES_PASSWORD: XMASPASSWORD
      POSTGRES_DB: pipeline
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    volumes:
      - ./volumes/data:/app/data
    command: 
      - /app/data/payments.csv
      - /app/data/providers.csv
      - /app/data/ex_rates.csv
    depends_on:
      - db

  mlflow:
    build: ./services/ai-python-service
    restart: always
    environment:
      PORT: 3000
    depends_on:
      - backend